[build]
  publish = "."
  functions = "functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
