[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Redirect /admin to /index.html cleanly without URL page reload
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
